<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Political Economy &amp; Data Analysis: Capstone Paper!</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Final-Edit_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final-Edit_files/libs/quarto-html/quarto.js"></script>
<script src="Final-Edit_files/libs/quarto-html/popper.min.js"></script>
<script src="Final-Edit_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final-Edit_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final-Edit_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final-Edit_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final-Edit_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final-Edit_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final-Edit_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Final-Edit.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Political Economy &amp; Data Analysis: Capstone Paper!</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-synopsis" class="level4">
<h4 class="anchored" data-anchor-id="introduction-synopsis"><strong>Introduction &amp; Synopsis</strong></h4>
<p><em>How did the implementation of the U.S. 1994 Violent Crime Control &amp; Law Enforcement Act impact crime rates in the United States, and to what extent were these impacts statistically significant and substantively meaningful?</em></p>
<p>In this study, my investigation centers on dissecting a two-part question: First, <em>did the U.S. 1994 Violent Crime Control &amp; Law Enforcement Act lead to a statistically significant change in crime rates?</em> Second, <em>If such a change is observed, to what extent is it substantively meaningful within the broader societal and economic landscape?</em> To address these inquiries, I utilize a comprehensive dataset spanning from 1986 to 2002. This dataset was meticulously assembled through the APIs of the FBI’s Crime Data Explorer (CDE), the Bureau of Economic Analysis, and the U.S. Federal Reserve Bank (FRED).</p>
<p>Employing advanced analytical methods, namely Difference-in-Differences analysis and Synthetic Control Estimation, my findings reveal a significant and pronounced impact of the 1994 Violent Crime Control and Law Enforcement Act on overall crime rates, particularly on violent crime. Specifically, the analysis indicates that, post-1994 VCCA ratification and implementation, states with high crime rates experienced an average reduction of 114.69 in violent crime rates. Similarly, these states also saw an average decrease of 327.46 in property crime rates. While these results were generally robust, it’s noteworthy that the property crime rate estimation underwent a notable shift in its significance and statistical support when the time frame of the analysis was adjusted.</p>
</section>
<section id="liturature-review-historical-context" class="level2">
<h2 class="anchored" data-anchor-id="liturature-review-historical-context"><strong>Liturature Review &amp; Historical Context</strong></h2>
<p>The <strong>Violent Crime Control &amp; Law Enforcement Act</strong> of 1994 (VCCA), often known as the 1994 Crime Bill, is a pivotal piece of U.S. legislation, renowned for its comprehensive scope and significant funding. Signed by President Bill Clinton, this extensive crime bill introduced several key measures to enhance public safety and reduce crime.</p>
<p>It initiated a 10-year federal ban on the manufacturing, sale, and possession of new semi-automatic assault weapons. The bill also established a federal “three strikes” rule, imposing life sentences for those convicted of a violent felony after two or more prior convictions, including drug offenses. Notably, it provided $8.8 billion for adding 100,000 new police officers, promoting community policing through the Community Oriented Policing Services (COPS) program, and created the COPS Grant program to support police hiring and equipment upgrades in applicant police and sheriff departments.</p>
<p>Furthermore, the 1994 Violent Crime Control &amp; Law Enforcement Act (VCCA) expanded the federal death penalty to include about 60 additional crimes, and incorporated the Violence Against Women Act, allocating $1.6 billion towards the investigation and prosecution of violent crimes against women. It provided funding for drug courts for alternative sentencing of drug offenders, and allocated $9.7 billion for federal prisons. The bill also supported various crime prevention programs, especially targeting youth.</p>
<p>In addition to these measures, the bill included the Brady Handgun Violence Prevention Act, which implemented federal background checks on firearm purchasers in the United States, established a framework for a national sex offender registry, and streamlined deportation proceedings for non-citizens convicted of crimes.</p>
<p>Concerning the topic abating crime, while there has been a bevy of liturature produced in the last two decades substatiating the effects of the police on crime <a href="https://www.aeaweb.org/articles?id=10.1257/00028280260344768">McCrary (2002)</a>, <a href="https://www.sciencedirect.com/science/article/abs/pii/S0047272718302305">Mello (2019)</a>, <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0157223">MacDonald 2016</a> - particularly, the effect of police presence on crime - some recent studies have investigated the effect that punishment and severity type has on crime. <a href="https://www.nber.org/system/files/chapters/c12078/c12078.pdf">Durlauf and Nagin (2011)</a> argues that severity-based sanctions, such as lengthy prison terms, have a modest marginal deterrent effect on crime. They suggest that a shift towards certainty-based sanctions, like effective and visible policing, could reduce both crime and imprisonment rates without increasing the overall resource commitment to the criminal justice system.</p>
<p>Other studies have examined the factors influencing crime rates. <a href="https://www.jstor.org/stable/10.1086/209905">Grogger et al.&nbsp;(1998)</a> focused on time allocation and wages, suggesting that crime rises when potential earnings from legal work decline. <a href="https://inequality.stanford.edu/sites/default/files/media/_media/pdf/Reference%20Media/Gould,%20Weinberg,%20and%20Mustard_2002_Crime%20and%20the%20Legal%20System.pdf">Gould et al.&nbsp;(2002)</a> found further evidence that poor labor market conditions, particularly for young men, is associated with an increased criminality. A working paper by <a href="https://www.nber.org/system/files/working_papers/w28202/w28202.pdf">Chalfin et al.&nbsp;(2020)</a> provided further empirical evidence that additional policing can directly reduce homicides <a href="https://direct.mit.edu/rest/article-abstract/100/1/167/58429/Are-U-S-Cities-Underpoliced-Theory-and-Evidence?redirectedFrom=fulltext">(Chalfin &amp; Mccrary, 2017)</a>. This body of research, along with the insights from Durlauf and Nagin (2011) and <a href="https://www.nber.org/system/files/working_papers/w28202/w28202.pdf">Weisburst (Latest Paper)</a>, highlights the complex variables at play, including labor markets and law enforcement strength, in understanding current crime trends.</p>
<section id="methodology-and-research-goals" class="level3">
<h3 class="anchored" data-anchor-id="methodology-and-research-goals"><strong>Methodology and Research Goals</strong></h3>
<p>I will be leveraging both, <strong>Difference-in-Difference</strong> and <strong>Synthetic Controls</strong> model design. These estimation techniques, used in conjunction with data from the U.S Federal Bureau of Investigation (FBI), Bureau of Economic Analysis (BEA), Federal Reserve Bank (FRED), will be used to tease out what effect the 1994 Violent Crime Control &amp; Law Enforcement Act (VCCA) may have had on surging crime in the United States. The initial position of the paper is that the 1994 Violent Crime Control &amp; Law Enforcement Act (VCCA) had analytically verifiable effects on crime but was ultimately unimpactful in the overarching crime trends in the United States (Lee &amp; Mccrary, 2005; Hjalmarsson, 2009).</p>
</section>
</section>
<section id="empirical-framework-and-data-sources" class="level2">
<h2 class="anchored" data-anchor-id="empirical-framework-and-data-sources">Empirical Framework and Data Sources</h2>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources"><strong>Data Source(s)</strong></h3>
<p>The data utilized in this study were derived from two primary government sources. The Bureau of Economic Analysis (BEA) provided key economic indicators, while crime statistics were obtained from the Department of Justice and FBI’s National Incident-Based Reporting System (NIBRS).</p>
<p>From the BEA, the variable “employment” reflects the total number of jobs in a state, aggregated in units of ten thousand. Additionally, the state’s Gross Domestic Product (GDP) and population figures were acquired, with GDP figures scaled to tens of millions and population estimates to the nearest ten thousand.</p>
<p>The NIBRS contributed detailed crime statistics, focusing on the period from 1985 to 2010. Specifically, this study incorporated the violent crime rate and property crime rate, both standardized per 100,000 inhabitants to facilitate comparison.</p>
</section>
<section id="variable-definitions" class="level3">
<h3 class="anchored" data-anchor-id="variable-definitions">Variable Definitions:</h3>
<p><strong>GDP:</strong></p>
<p>This represents the BEA’s estimate of the total market value of goods and services produced within a state in a given fiscal year.</p>
<p><strong>Population:</strong></p>
<p>An estimation by the BEA, accounting for the base population of the previous year, adjusted for births, deaths, and net migration.</p>
<p><strong>Employment (emp):</strong></p>
<p>An estimate of total employment figures by the BEA, based on the North American Industry Classification System (NAICS), collected at the level of hundreds of thousands.</p>
<p><strong>Post-1994 Indicator:</strong></p>
<p>A dichotomous variable created to categorize the temporal data into two groups: before and after the enactment of the Violent Crime Control and Law Enforcement Act (VCCA) of 1994. This binary indicator serves to assess the impact of the VCCA on crime rates and economic factors.</p>
<p><strong>High Crime Indicator:</strong> For our analysis operationalizes the designation of “High Crime” states through a quantitative metric that encompasses states with violent crime rates exceeding one standard deviation above the national average. This statistical threshold was chosen based on the calculated national mean and standard deviation for violent crime, thereby identifying states with disproportionately high crime rates. Such a criterion is deliberate in isolating significant outliers, ensuring that the classification reflects a marked departure from the typical crime levels. This methodological choice underscores states where violent crime rates are not merely above average, but are also statistically aberrant, thereby meriting particular attention in policy planning and resource allocation. States where this indicator is equal to one are as follows: California, Illinois, Louisiana, Massachusetts, Maryland, Michigan, New Mexico, New York</p>
<p><strong>High Crime Property Indicator:</strong> For our analysis operationalizes the designation of “High Crime” states through a quantitative metric that encompasses states with property crime rates exceeding one standard deviation above the national average. This statistical threshold was chosen based on the calculated national mean and standard deviation for violent crime, thereby identifying states with disproportionately high property crime rates. Such a criterion is deliberate in isolating significant outliers, ensuring that the classification reflects a marked departure from the typical crime levels. This methodological choice underscores states where property crime rates are not merely above average, but are also statistically aberrant, thereby meriting particular attention in policy planning and resource allocation. States where this indicator is equal to 1 are as follows : Arizona, California, Colorado, Hawaii, Louisiana, Michigan, New Mexico, Nevada, New York, Oregon, Texas, Utah, Washington.</p>
<p><strong>Post-High Crime Statstic (PostHC_static):</strong> The variable “Post-High Crime Static” (PostHC_static) is designed to function within the Difference-in-Differences (DiD) estimation framework of this model. It identifies whether a data point pertains to a period after the implementation of the Violent Crime Control and Law Enforcement Act (VCCA) of 1994 within states classified as high-crime. This binary variable is crucial for assessing the differential impact of the VCCA’s enactment on states with elevated crime rates, relative to their counterparts.</p>
<p><strong>Violent Crime Rate:</strong></p>
<p>Estimated rate of violent crimes reported to the FBI for a given state and year. Includes within it are counts of:</p>
<ol type="1">
<li><p><strong>Criminal homicide</strong> : Murder and nonnegligent manslaughter: the willful (nonnegligent) killing of one human being by another. Deaths caused by negligence, attempts to kill, assaults to kill, suicides, and accidental deaths are excluded. The program classifies justifiable homicides separately and limits the definition to: (1) the killing of a felon by a law enforcement officer in the line of duty; or (2) the killing of a felon, during the commission of a felony, by a private citizen. b.) Manslaughter by negligence: the killing of another person through gross negligence. Deaths of persons due to their own negligence, accidental deaths not resulting from gross negligence, and traffic fatalities are not included in the category manslaughter by negligence.</p></li>
<li><p><strong>Robbery</strong> : The taking or attempting to take anything of value from the care, custody, or control of a person or persons by force or threat of force or violence and/or by putting the victim in fear.</p></li>
<li><p><strong>Aggravated assault</strong> : An unlawful attack by one person upon another for the purpose of inflicting severe or aggravated bodily injury. This type of assault usually is accompanied by the use of a weapon or by means likely to produce death or great bodily harm. Simple assaults are excluded.</p></li>
<li><p><strong>Other assaults (simple)</strong> : Assaults and attempted assaults where no weapon was used or no serious or aggravated injury resulted to the victim. Stalking, intimidation, coercion, and hazing are included.</p></li>
</ol>
<p><strong>Property Crime Rate</strong> :</p>
<p>Estimated rate of proeprty crimes reported to the FBI for a given state and year. Includes within it are counts of:</p>
<ol type="1">
<li><p><strong>Burglary</strong>: This includes unlawful entry into a building or other structure with the intent to commit theft or any felony. Burglaries can be classified into different types, such as forcible entry, unlawful entry where no force is used, and attempted forcible entry.</p></li>
<li><p><strong>Larceny-Theft</strong>: This encompasses crimes such as shoplifting, pickpocketing, purse snatching, thefts from motor vehicles (including parts and accessories), bicycle thefts, thefts from buildings, and other forms of theft where there is no use of force, violence, or fraud. It excludes embezzlement, confidence games, forgery, check fraud, etc.</p></li>
<li><p><strong>Motor Vehicle Theft</strong>: This includes the theft or attempted theft of a motor vehicle, which encompasses all cases where automobiles are taken by persons not having lawful access, even if the vehicle is later abandoned.</p></li>
</ol>
</section>
</section>
<section id="exploritory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploritory-data-analysis-eda">Exploritory Data Analysis (EDA):</h2>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 25%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Population</th>
<th>Employment</th>
<th>Violent Crime Rate</th>
<th>Property Crime Rate</th>
<th>GDP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td>663</td>
<td>663</td>
<td>663</td>
<td>663</td>
<td>663</td>
</tr>
<tr class="even">
<td>mean</td>
<td>5595.85</td>
<td>2481.25</td>
<td>525.628</td>
<td>4384.16</td>
<td>156576</td>
</tr>
<tr class="odd">
<td>std</td>
<td>6063.95</td>
<td>2597.34</td>
<td>225.846</td>
<td>999.122</td>
<td>193749</td>
</tr>
<tr class="even">
<td>min</td>
<td>453.401</td>
<td>183.1</td>
<td>51.3</td>
<td>2206.6</td>
<td>9744</td>
</tr>
<tr class="odd">
<td>25%</td>
<td>1650.49</td>
<td>666.2</td>
<td>349.45</td>
<td>3738.4</td>
<td>37049</td>
</tr>
<tr class="even">
<td>50%</td>
<td>4048.51</td>
<td>1670.4</td>
<td>514.6</td>
<td>4245.2</td>
<td>95024</td>
</tr>
<tr class="odd">
<td>75%</td>
<td>6341.34</td>
<td>3071.5</td>
<td>679.05</td>
<td>5052.6</td>
<td>188025</td>
</tr>
<tr class="even">
<td>max</td>
<td>34871.8</td>
<td>14720</td>
<td>1180.9</td>
<td>7500.1</td>
<td>1.36778e+06</td>
</tr>
</tbody>
</table>
</section>
<section id="descriptive-statistics-overall" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-overall"><strong>Descriptive Statistics (Overall):</strong></h2>
<p><strong>Population:</strong> The average state population in the dataset is approximately 5,628 individuals, with a median of 4,074, suggesting a right-skewed distribution. The standard deviation is significant at 6,104, indicating considerable variation in state populations. The distribution exhibits a pronounced right skew (skewness = 2.44) and a high kurtosis value of 6.98, reflecting a distribution with heavy tails and a sharp peak.</p>
<p><strong>Employment:</strong> Employment figures average at about 2,497, with a median of 1,675, which also indicates a right-skewed distribution. The standard deviation is 2,613, and like population, there is substantial variation across the dataset. The skewness is 2.18, and the kurtosis is 5.54, which means that the employment distribution also has a long right tail with a peak higher than a normal distribution.</p>
<p><strong>Violent Crime Rate:</strong> The average violent crime rate per 100,000 inhabitants is about 519.92, with a median rate of 509.90, suggesting a distribution that is slightly skewed to the right (skewness = 0.33). The standard deviation is 223.81, and the kurtosis is -0.22, indicating a distribution that is slightly flatter than a normal distribution.</p>
<p><strong>Property Crime Rate:</strong> This rate averages 4,341.59 per 100,000 inhabitants, with a median of 4,219.85, also slightly right-skewed (skewness = 0.37). The standard deviation is 1,005.37, and the kurtosis is 0.05, which suggests a distribution close to normal.</p>
<p><strong>GDP:</strong> The average GDP is significantly skewed with a mean of approximately 160,978 and a median of 95,585, indicating a highly right-skewed distribution (skewness = 2.96). The standard deviation is 199,877, and the kurtosis is extremely high at 11.20. suggesting that a few states have very high GDP values compared to the majority.</p>
</section>
<section id="descriptive-statistics-high-crime-states" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-high-crime-states"><strong>Descriptive Statistics (High Crime States):</strong></h2>
<p><strong>Population:</strong> The average population of “High Crime” states is approximately 9,169, with a median of 5,375, indicating a right-skewed distribution. The standard deviation is high at 8,870, showing significant variation in population sizes among these states. The skewness (1.38) and kurtosis (1.09) suggest a moderately peaked and right-skewed distribution.</p>
<p><strong>Employment:</strong> The average employment in “High Crime” states is around 3,983, with a median of 2,473. The standard deviation is 3,720, reflecting substantial variability in employment levels. The skewness (1.25) and kurtosis (0.70) indicate a distribution that is right-skewed and has a slightly higher peak than a normal distribution.</p>
<p><strong>Violent Crime Rate:</strong> The average violent crime rate is significantly higher in “High Crime” states at approximately 759.50 per 100,000 inhabitants, with a median of 757.90, suggesting a symmetric distribution. The standard deviation is 157.64, and the distribution has a slight right skew (skewness = 0.46) and is somewhat flatter than a normal distribution (kurtosis = -0.42).</p>
<p><strong>Property Crime Rate:</strong> “High Crime” states have an average property crime rate of approximately 4,709.75 per 100,000 inhabitants, with a median of 4,675.40. The standard deviation is 953.44, indicating variability in the property crime rates. The distribution is almost symmetric (skewness = 0.11) and has a kurtosis of 0.15, suggesting it is very close to normal.</p>
<p><strong>GDP:</strong> The GDP of “High Crime” states averages at 274,605 with a high standard deviation of 295,486, suggesting significant economic disparity among these states. The distribution is right-skewed (skewness = 1.79) and has a higher peak (kurtosis = 3.07) compared to a normal distribution, indicating a concentration of states with lower GDP values and a few outliers with very high GDPs.</p>
<p>The data indicates that “High Crime” states are not homogenous; they exhibit considerable variation in population, employment levels, and economic output. The crime rates, while on average higher than the threshold for “High Crime” classification, do not present extreme variability in their distribution, suggesting that once a state is categorized as “High Crime,” its crime rates tend to be elevated but within a certain range.</p>
<section id="maps-of-the-united-states-high-violent-crime" class="level4">
<h4 class="anchored" data-anchor-id="maps-of-the-united-states-high-violent-crime">Maps Of the United States (High Violent Crime)</h4>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-3-output-1.png" width="1162" height="753"></p>
</div>
</div>
</section>
<section id="high-property-crime" class="level4">
<h4 class="anchored" data-anchor-id="high-property-crime">High property Crime:</h4>
<div class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-4-output-1.png" width="1162" height="753"></p>
</div>
</div>
</section>
</section>
<section id="modelsresults-analysis" class="level2">
<h2 class="anchored" data-anchor-id="modelsresults-analysis"><strong>Model(s),Results &amp; Analysis:</strong></h2>
<p><strong>The following models will be estimated in two parts:</strong> - Model set 1: where the models are estimated without Fixed Effects nor Standard error clustering, in both Python and R for comparison. - Model set 2: Where the models are estimated inclduing Fixed Effects and Standard error clustering, in both R and Python for comparison.</p>
<p><strong>Model-01: State-Level Violent Crime Rate</strong></p>
<p><span class="math display">\[
\text{Violent\_Crime}_i = \beta_0 + \beta_1 \text{employment}_i + \beta_2 \text{population}_i + \beta_3 \text{Post\_1994}_i + \beta_4 \text{High\_Crime}_i + \beta_5 \text{Post\_HC\_s}_i + \epsilon_i
\]</span></p>
<p><strong>Model-02: State-level Property Crime Rate</strong></p>
<p><span class="math display">\[
\text{Property\_Crime}_i = \omega_0 + \omega_1 \text{employment}_i + \omega_2 \text{population}_i + \omega_3 \text{Post\_1994}_i + \omega_4 \text{High\_Crime\_Prop}_i + \omega_5 \text{Post\_PC}_i + \eta_i
\]</span></p>
<section id="model-01a" class="level4">
<h4 class="anchored" data-anchor-id="model-01a"><strong>Model-01A:</strong></h4>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>violent_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.450</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.446</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>107.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 12 Dec 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>7.47e-83</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:46</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-4335.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>663</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>8683.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>657</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>8710.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>5</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>445.8156</td>
<td>11.194</td>
<td>39.825</td>
<td>0.000</td>
<td>423.834</td>
<td>467.797</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">employment</td>
<td>-0.0539</td>
<td>0.030</td>
<td>-1.792</td>
<td>0.074</td>
<td>-0.113</td>
<td>0.005</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">population</td>
<td>0.0302</td>
<td>0.013</td>
<td>2.344</td>
<td>0.019</td>
<td>0.005</td>
<td>0.055</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Post_1994</td>
<td>-34.9076</td>
<td>15.413</td>
<td>-2.265</td>
<td>0.024</td>
<td>-65.172</td>
<td>-4.644</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">High Crime</td>
<td>354.9056</td>
<td>23.631</td>
<td>15.019</td>
<td>0.000</td>
<td>308.505</td>
<td>401.306</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Post_HC</td>
<td>-119.6531</td>
<td>32.430</td>
<td>-3.690</td>
<td>0.000</td>
<td>-183.331</td>
<td>-55.975</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>5.137</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>0.150</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.077</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>4.602</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.141</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.100</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>2.704</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>5.18e+04</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br>[2] The condition number is large, 5.18e+04. This might indicate that there are<br>strong multicollinearity or other numerical problems.
</div>
</div>
<div class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
MODEL INFO:
Observations: 663
Dependent Variable: Y
Type: OLS linear regression 

MODEL FIT:
F(5,657) = 107.46150, p = 0.00000
R² = 0.44989
Adj. R² = 0.44570 

Standard errors: OLS
----------------------------------------------------------------------------
                          Est.         2.5%       97.5%     t val.         p
----------------- ------------ ------------ ----------- ---------- ---------
(Intercept)          445.81562    423.83445   467.79678   39.82478   0.00000
employment            -0.05391     -0.11298     0.00515   -1.79242   0.07352
population             0.03016      0.00490     0.05542    2.34440   0.01935
Post_1994            -34.90756    -65.17156    -4.64356   -2.26486   0.02385
High.Crime           354.90560    308.50507   401.30613   15.01892   0.00000
Post_HC             -119.65315   -183.33145   -55.97485   -3.68962   0.00024
----------------------------------------------------------------------------
</code></pre>
</div>
</div>
</section>
<section id="model-01b" class="level4">
<h4 class="anchored" data-anchor-id="model-01b"><strong>Model-01B:</strong></h4>
<div class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>property_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.522</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.518</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>143.4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 12 Dec 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>9.22e-103</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:46</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5274.9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>663</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>1.056e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>657</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>1.059e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>5</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>4319.3923</td>
<td>49.867</td>
<td>86.619</td>
<td>0.000</td>
<td>4221.475</td>
<td>4417.310</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">employment</td>
<td>-0.3646</td>
<td>0.128</td>
<td>-2.849</td>
<td>0.005</td>
<td>-0.616</td>
<td>-0.113</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">population</td>
<td>0.1313</td>
<td>0.055</td>
<td>2.386</td>
<td>0.017</td>
<td>0.023</td>
<td>0.239</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Post_1994</td>
<td>-446.3962</td>
<td>68.805</td>
<td>-6.488</td>
<td>0.000</td>
<td>-581.501</td>
<td>-311.291</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">High Crime Prop</td>
<td>1552.2267</td>
<td>81.961</td>
<td>18.939</td>
<td>0.000</td>
<td>1391.289</td>
<td>1713.164</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Post_PC</td>
<td>-464.8241</td>
<td>114.629</td>
<td>-4.055</td>
<td>0.000</td>
<td>-689.908</td>
<td>-239.740</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>0.939</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>0.299</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.625</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>0.817</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>-0.080</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.665</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>3.064</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>4.61e+04</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br>[2] The condition number is large, 4.61e+04. This might indicate that there are<br>strong multicollinearity or other numerical problems.
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>MODEL INFO:
Observations: 663
Dependent Variable: Y
Type: OLS linear regression 

MODEL FIT:
F(5,657) = 143.41639, p = 0.00000
R² = 0.52186
Adj. R² = 0.51822 

Standard errors: OLS
---------------------------------------------------------------------------------
                              Est.         2.5%        97.5%     t val.         p
--------------------- ------------ ------------ ------------ ---------- ---------
(Intercept)             4319.39235   4221.47509   4417.30961   86.61882   0.00000
employment                -0.36457     -0.61581     -0.11332   -2.84924   0.00452
population                 0.13133      0.02326      0.23941    2.38619   0.01731
Post_1994               -446.39615   -581.50118   -311.29112   -6.48781   0.00000
High.Crime.Prop         1552.22675   1391.28909   1713.16440   18.93853   0.00000
Post_PC                 -464.82413   -689.90833   -239.73992   -4.05502   0.00006
---------------------------------------------------------------------------------
</code></pre>
</div>
</div>
</section>
<section id="model-01c-comprehensive-step-wise-model-progrssion-for-violent-property-crime-rate" class="level4">
<h4 class="anchored" data-anchor-id="model-01c-comprehensive-step-wise-model-progrssion-for-violent-property-crime-rate"><strong>Model-01C: Comprehensive Step-Wise Model Progrssion For Violent &amp; Property Crime Rate</strong></h4>
<div class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Violent Crime Rate Models:
 
=================================================================
                Model 1   Model 2   Model 3   Model 4   Model 5  
-----------------------------------------------------------------
High Crime                                   299.03*** 354.91*** 
                                             (18.31)   (23.63)   
Post_1994                          -64.25*** -58.68*** -34.91**  
                                   (16.74)   (14.13)   (15.41)   
Post_HC                                                -119.65***
                                                       (32.43)   
R-squared      0.17      0.19      0.21      0.44      0.45      
R-squared Adj. 0.17      0.19      0.21      0.44      0.45      
const          435.79*** 446.00*** 470.45*** 457.68*** 445.82*** 
               (11.04)   (11.20)   (12.79)   (10.82)   (11.19)   
employment     0.04***   -0.10***  -0.05     -0.06*    -0.05*    
               (0.00)    (0.03)    (0.04)    (0.03)    (0.03)    
population               0.06***   0.04**    0.03**    0.03**    
                         (0.01)    (0.02)    (0.01)    (0.01)    
R-squared      0.17      0.19      0.21      0.44      0.45      
N              663       663       663       663       663       
=================================================================
Standard errors in parentheses.
* p&lt;.1, ** p&lt;.05, ***p&lt;.01

Property Crime Rate Models:
 
======================================================================
                 Model 1    Model 2    Model 3    Model 4    Model 5  
----------------------------------------------------------------------
High Crime Prop                                  1332.42*** 1552.23***
                                                 (62.19)    (81.96)   
Post_1994                             -500.40*** -597.13*** -446.40***
                                      (76.03)    (58.58)    (68.81)   
Post_PC                                                     -464.82***
                                                            (114.63)  
R-squared       0.00       0.11       0.17       0.51       0.52      
R-squared Adj.  -0.00      0.11       0.16       0.51       0.52      
const           4395.89*** 4503.57*** 4693.98*** 4395.41*** 4319.39***
                (53.72)    (51.97)    (58.09)    (46.75)    (49.87)   
employment      -0.00      -1.44***   -1.07***   -0.39***   -0.36***  
                (0.01)     (0.16)     (0.16)     (0.13)     (0.13)    
population                 0.62***    0.46***    0.14**     0.13**    
                           (0.07)     (0.07)     (0.06)     (0.06)    
R-squared       0.00       0.11       0.17       0.51       0.52      
N               663        663        663        663        663       
======================================================================
Standard errors in parentheses.
* p&lt;.1, ** p&lt;.05, ***p&lt;.01</code></pre>
</div>
</div>
</section>
</section>
<section id="model-series-1-violent-crime-result-analysis" class="level2">
<h2 class="anchored" data-anchor-id="model-series-1-violent-crime-result-analysis"><strong>Model Series 1: Violent Crime Result Analysis</strong></h2>
<p><strong>Employment:</strong> In the final violent crime rate model we that the “employment” control is borderline significant at the 10% level with an estiamted effect of -0.05391 suggesting that, at the 10% level, for every additional person employed there is an associated drop of roughly 5% in the violent crime rate (per 100,000). Looking at the comprehensive results from figure 01C, we notice a material change in significance of the “employment” variable with inclusion of additional controls with the largest change occuring with the inclusion of the “Post_1994” variable, which remove all significance from the “employment” variable in the analysis.</p>
<p>Concerning the estimated effect magnititude, the range of the effect occulates between 4% and 10% which is relatively large, with the largest estimated effect (10%) occuring in the second model that includes a population control.</p>
<p><strong>Population:</strong> In the final model, population is significant at the 5% level and has an estimated effect of 0.03 or 3%. This suggests that for every per person increase in popuation, there is an associated increase the violent crime rate. Through out models 2-5, population retains it’s significance with the high significance occuring in the second model - the first with population included - with it being significance at the 1% level. It’s also in the second model where it has it’s larghest estimated effect of .06 or 6%.</p>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis"><strong>Analysis:</strong></h2>
<section id="model-vc-violent-crime-rate" class="level3">
<h3 class="anchored" data-anchor-id="model-vc-violent-crime-rate">Model VC (Violent Crime Rate)</h3>
<section id="regression-results" class="level4">
<h4 class="anchored" data-anchor-id="regression-results">Regression Results:</h4>
<ol type="1">
<li><p><strong>Constant (Intercept)</strong>: The model’s intercept is 445.8156 with a standard error of 11.194, highly significant (p &lt; 0.001). This suggests that, holding all other variables at zero, the expected violent crime rate is 445.82 per 100,000 population. However, the interpretation of the intercept is more notional than practical, as the scenario of all other variables being zero is unrealistic.</p></li>
<li><p><strong>Employment</strong>: The coefficient is -0.0539 (p = 0.074), indicating a marginally significant negative relationship between employment and violent crime rate. For every one-unit increase in employment (presumably measured in thousands or some consistent unit), the violent crime rate decreases by approximately 0.054 per 100,000 population. This aligns with economic theories suggesting that higher employment can lead to reduced crime rates due to better social and economic opportunities.</p></li>
<li><p><strong>Population</strong>: The coefficient of 0.0302 (p = 0.019) implies a positive relationship between population size and violent crime rate. This coefficient is statistically significant, suggesting that larger populations are associated with higher rates of violent crime, potentially due to increased anonymity and opportunities for crime in more populous areas.</p></li>
<li><p><strong>Post_1994</strong>: The coefficient is -34.9076 (p = 0.024), indicating a statistically significant decrease in violent crime rate post-1994, which could be interpreted as the effect of the VCCA. This suggests that following the enactment of the VCCA, violent crime rates decreased by about 34.91 per 100,000 population, all else being equal.</p></li>
<li><p><strong>High Crime</strong>: With a coefficient of 354.9056 (p &lt; 0.001), this variable shows a significant positive association with the violent crime rate. This could indicate areas previously designated as ‘high crime’ continue to experience elevated levels of violent crime.</p></li>
<li><p><strong>Post_HC</strong>: The coefficient is -119.6531 (p &lt; 0.001), suggesting a significant reduction in violent crime rates in areas that were high crime before 1994 and after the enactment of VCCA. This might imply that VCCA had a particularly strong impact in previously high-crime areas.</p></li>
</ol>
</section>
</section>
<section id="model-pc-property-crime-rate" class="level3">
<h3 class="anchored" data-anchor-id="model-pc-property-crime-rate">Model PC (Property Crime Rate)</h3>
<section id="regression-results-1" class="level4">
<h4 class="anchored" data-anchor-id="regression-results-1">Regression Results:</h4>
<ol type="1">
<li><p><strong>Constant (Intercept)</strong>: The intercept is 4319.3923 with a standard error of 49.867, highly significant (p &lt; 0.001). This implies a baseline property crime rate of 4319.39 per 100,000 population, under the hypothetical scenario where all other predictors are zero.</p></li>
<li><p><strong>Employment</strong>: The coefficient is -0.3646 (p = 0.005), suggesting a significant negative relationship between employment and property crime rate. This supports the theory that higher employment levels can reduce property crime, possibly due to improved economic conditions.</p></li>
<li><p><strong>Population</strong>: The positive coefficient of 0.1313 (p = 0.017) indicates a significant relationship between larger population sizes and higher property crime rates, consistent with the theory of increased criminal opportunities in more populous areas.</p></li>
<li><p><strong>Post_1994</strong>: The coefficient is -446.3962 (p &lt; 0.001), showing a substantial decrease in property crime rate post-1994. This robust result could be interpreted as the impact of the VCCA on property crimes, suggesting a significant policy effectiveness.</p></li>
<li><p><strong>High Crime Prop</strong>: The coefficient of 1552.2267 (p &lt; 0.001) indicates a strong positive association with property crime rate in areas designated as high crime for property offenses. This is consistent with the notion that areas with historically high property crime rates continue to experience elevated levels.</p></li>
<li><p><strong>Post_PC</strong>: The coefficient of -464.8241 (p &lt; 0.001) suggests a significant reduction in property crime rates in specific areas post-VCCA, possibly indicating the effectiveness of the policy in targeted locations.</p></li>
</ol>
</section>
</section>
<section id="overall-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="overall-interpretation">Overall Interpretation:</h3>
<p>Both models show that the VCCA’s enactment is associated with significant decreases in both violent and property crime rates, as evidenced by the negative coefficients of the Post_1994 variable in both models. This is a key finding, suggesting that the policy had a tangible impact on crime rates across the board. The interaction terms (Post_HC_s in the violent crime model and Post_PC in the property crime model) further indicate that these effects were particularly pronounced in areas that were already struggling with high crime rates, highlighting the targeted effectiveness of the policy.</p>
<p>The relationships between crime rates and population, as well as employment, align with conventional criminological and economic theories. Larger populations are correlated with higher crime rates, likely due to increased opportunities and anonymity for criminals. Conversely, higher employment is associated with lower crime rates, supporting the theory that improved economic conditions can reduce criminal incentives.</p>
<p>It’s important to note that while these results are statistically significant and align with theoretical expectations, they are subject to the usual caveats of regression analysis, including potential omitted variable bias and the assumption of a linear relationship between the predictors and the dependent variable.</p>
</section>
</section>
<section id="model-02a-panelols-with-state-and-year-fixed-effects-with-state-time-standard-error-clustering" class="level2">
<h2 class="anchored" data-anchor-id="model-02a-panelols-with-state-and-year-fixed-effects-with-state-time-standard-error-clustering"><strong>Model-02A: PanelOLS with State and Year Fixed Effects with State-Time Standard Error Clustering</strong></h2>
<div class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>PanelOLS Estimation Summary</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>violent_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.2052</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Estimator:</td>
<td>PanelOLS</td>
<td data-quarto-table-cell-role="th">R-squared (Between):</td>
<td>-1.3341</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>702</td>
<td data-quarto-table-cell-role="th">R-squared (Within):</td>
<td>0.2524</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, Dec 12 2023</td>
<td data-quarto-table-cell-role="th">R-squared (Overall):</td>
<td>-1.2901</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:47</td>
<td data-quarto-table-cell-role="th">Log-likelihood</td>
<td>-3895.9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cov. Estimator:</td>
<td>Clustered</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>55.323</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Entities:</td>
<td>39</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,643)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th">F-statistic (robust):</td>
<td>13.022</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time periods:</td>
<td>18</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,643)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Parameter Estimates</caption>
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">Parameter</td>
<td data-quarto-table-cell-role="th">Std. Err.</td>
<td data-quarto-table-cell-role="th">T-stat</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td data-quarto-table-cell-role="th">Lower CI</td>
<td data-quarto-table-cell-role="th">Upper CI</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">employment</td>
<td>-0.0073</td>
<td>0.0651</td>
<td>-0.1119</td>
<td>0.9109</td>
<td>-0.1351</td>
<td>0.1205</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">population</td>
<td>-0.0364</td>
<td>0.0300</td>
<td>-1.2145</td>
<td>0.2250</td>
<td>-0.0953</td>
<td>0.0225</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Post_HC</td>
<td>-114.69</td>
<td>52.681</td>
<td>-2.1772</td>
<td>0.0298</td>
<td>-218.14</td>
<td>-11.248</td>
</tr>
</tbody>
</table>
<br><br>F-test for Poolability: 107.61<br>P-value: 0.0000<br>Distribution: F(55,643)<br><br>Included effects: Entity, Time
</div>
</div>
<section id="model-02a-part-b-panelols-with-state-and-year-fixed-effects-with-state-time-standard-error-clustering-using-plm-package-in-r" class="level4">
<h4 class="anchored" data-anchor-id="model-02a-part-b-panelols-with-state-and-year-fixed-effects-with-state-time-standard-error-clustering-using-plm-package-in-r"><strong>Model-02A-Part B: PanelOLS with State and Year Fixed Effects with State-Time Standard Error Clustering Using PLM Package in R</strong></h4>
<div class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Twoways effects Within Model

Call:
plm(formula = violent_crime_rate ~ Post_HC + employment + population, 
    data = pdata, effect = "twoways", model = "within")

Balanced Panel: n = 39, T = 17, N = 663

Residuals:
     Min.   1st Qu.    Median   3rd Qu.      Max. 
-224.6549  -38.7036   -1.9129   37.2119  232.3728 

Coefficients:
              Estimate  Std. Error t-value  Pr(&gt;|t|)    
Post_HC    -105.029641   12.676650 -8.2853 7.605e-16 ***
employment   -0.014219    0.024247 -0.5864   0.55781    
population   -0.033616    0.013448 -2.4997   0.01269 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Total Sum of Squares:    3116300
Residual Sum of Squares: 2541700
R-Squared:      0.18438
Adj. R-Squared: 0.10754
F-statistic: 45.5899 on 3 and 605 DF, p-value: &lt; 2.22e-16
                Estimate  Std. Error    t-value   Pr(&gt;|t|)
Post_HC    -105.02964095 49.35619087 -2.1279932 0.03374125
employment   -0.01421909  0.05800263 -0.2451456 0.80642679
population   -0.03361626  0.02882938 -1.1660418 0.24405701</code></pre>
</div>
</div>
</section>
<section id="model-02b-property-crime-rate-with-fixed-effects-and-clustered-standard-errors" class="level4">
<h4 class="anchored" data-anchor-id="model-02b-property-crime-rate-with-fixed-effects-and-clustered-standard-errors"><strong>Model-02B: Property Crime Rate with Fixed Effects and Clustered Standard Errors</strong></h4>
<div class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>PanelOLS Estimation Summary</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>property_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.1937</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Estimator:</td>
<td>PanelOLS</td>
<td data-quarto-table-cell-role="th">R-squared (Between):</td>
<td>-0.9805</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>702</td>
<td data-quarto-table-cell-role="th">R-squared (Within):</td>
<td>0.3388</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, Dec 12 2023</td>
<td data-quarto-table-cell-role="th">R-squared (Overall):</td>
<td>-0.9577</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:47</td>
<td data-quarto-table-cell-role="th">Log-likelihood</td>
<td>-5077.1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cov. Estimator:</td>
<td>Clustered</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>51.474</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Entities:</td>
<td>39</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,643)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>18.000</td>
<td data-quarto-table-cell-role="th">F-statistic (robust):</td>
<td>15.682</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time periods:</td>
<td>18</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,643)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Parameter Estimates</caption>
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">Parameter</td>
<td data-quarto-table-cell-role="th">Std. Err.</td>
<td data-quarto-table-cell-role="th">T-stat</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td data-quarto-table-cell-role="th">Lower CI</td>
<td data-quarto-table-cell-role="th">Upper CI</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">employment</td>
<td>0.0799</td>
<td>0.3223</td>
<td>0.2480</td>
<td>0.8042</td>
<td>-0.5530</td>
<td>0.7129</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">population</td>
<td>-0.3050</td>
<td>0.1658</td>
<td>-1.8398</td>
<td>0.0663</td>
<td>-0.6305</td>
<td>0.0205</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Post_PC</td>
<td>-327.46</td>
<td>185.60</td>
<td>-1.7644</td>
<td>0.0781</td>
<td>-691.91</td>
<td>36.985</td>
</tr>
</tbody>
</table>
<br><br>F-test for Poolability: 79.274<br>P-value: 0.0000<br>Distribution: F(55,643)<br><br>Included effects: Entity, Time
</div>
</div>
</section>
</section>
<section id="model-02b_partb-property-crime-rate-with-fixed-effects-and-clustered-standard-errors-using-plm-in-r" class="level2">
<h2 class="anchored" data-anchor-id="model-02b_partb-property-crime-rate-with-fixed-effects-and-clustered-standard-errors-using-plm-in-r"><strong>Model-02B_PartB: Property Crime Rate with Fixed Effects and Clustered Standard Errors Using PLM in R</strong></h2>
<div class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Twoways effects Within Model

Call:
plm(formula = property_crime_rate ~ Post_PC + employment + population, 
    data = pdata, effect = "twoways", model = "within")

Balanced Panel: n = 39, T = 17, N = 663

Residuals:
    Min.  1st Qu.   Median  3rd Qu.     Max. 
-873.681 -210.084  -11.643  189.787 1190.259 

Coefficients:
              Estimate  Std. Error t-value  Pr(&gt;|t|)    
Post_PC    -305.556298   61.480114 -4.9700 8.728e-07 ***
employment    0.096685    0.130097  0.7432    0.4577    
population   -0.346606    0.073208 -4.7345 2.738e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Total Sum of Squares:    91503000
Residual Sum of Squares: 73271000
R-Squared:      0.19925
Adj. R-Squared: 0.12381
F-statistic: 50.1803 on 3 and 605 DF, p-value: &lt; 2.22e-16
                Estimate  Std. Error    t-value   Pr(&gt;|t|)
Post_PC    -305.55629785 166.8797606 -1.8309967 0.06759268
employment    0.09668516   0.2987478  0.3236347 0.74632646
population   -0.34660559   0.1656886 -2.0919096 0.03686289</code></pre>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion"><strong>Discussion:</strong></h2>
<section id="model-1-violent-crime-rate" class="level3">
<h3 class="anchored" data-anchor-id="model-1-violent-crime-rate">Model 1: Violent Crime Rate</h3>
<section id="regression-results-2" class="level4">
<h4 class="anchored" data-anchor-id="regression-results-2">Regression Results:</h4>
<ol type="1">
<li><p><strong>Employment</strong>: The coefficient is -0.0142, with a standard error of 0.0633 and a t-statistic of -0.2245, yielding a p-value of 0.8225. This indicates that there is no statistically significant relationship between employment and violent crime rate in this model. The implication is that within the scope of this model, employment changes are not strong predictors of variations in violent crime rates.</p></li>
<li><p><strong>Population</strong>: The coefficient is -0.0336 with a standard error of 0.0295. The t-statistic is -1.1408, resulting in a p-value of 0.2544. Again, this variable does not show statistical significance at conventional levels, suggesting that within the confines of this model, population changes do not significantly influence violent crime rates.</p></li>
<li><p><strong>Post_HC_s</strong>: The coefficient of -105.03 with a standard error of 52.303 and a t-statistic of -2.0081 is statistically significant at the 5% level (p-value = 0.0451). This suggests a significant decrease in violent crime rates in the post-intervention period in areas with historically high crime rates. This finding is crucial as it implies a tangible impact of the interventions targeting high crime areas.</p></li>
</ol>
</section>
<section id="model-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics:</h4>
<ul>
<li><strong>R-squared (Within)</strong>: At 0.2204, it indicates that about 22.04% of the variation in violent crime rates is explained by the model within entities (i.e., controlling for entity-specific characteristics).</li>
<li><strong>F-statistic</strong>: Highly significant (p-value &lt; 0.0001), indicating the model’s explanatory variables have a collective significance.</li>
<li><strong>Poolability Test</strong>: The F-test for poolability is significant, suggesting that entity and time effects are important in this model.</li>
</ul>
</section>
</section>
<section id="model-2-property-crime-rate" class="level3">
<h3 class="anchored" data-anchor-id="model-2-property-crime-rate">Model 2: Property Crime Rate</h3>
<section id="regression-results-3" class="level4">
<h4 class="anchored" data-anchor-id="regression-results-3">Regression Results:</h4>
<ol type="1">
<li><p><strong>Employment</strong>: The coefficient is 0.0967, with a standard error of 0.3117, resulting in a t-statistic of 0.3102 and a p-value of 0.7566. This implies no statistically significant relationship between employment and property crime rate.</p></li>
<li><p><strong>Population</strong>: The coefficient of -0.3466 is significant at the 5% level (p-value = 0.0423) with a t-statistic of -2.0349. This suggests that population changes have a statistically significant impact on property crime rates, with larger populations associated with lower property crime rates in this context.</p></li>
<li><p><strong>Post_PC</strong>: The coefficient is -305.56, with a standard error of 188.10 and a t-statistic of -1.6244. The p-value of 0.1048 indicates that this variable is not significant at the conventional 5% level. This suggests that the post-intervention effect on property crime rates is not statistically significant within the scope of this model.</p></li>
</ol>
</section>
<section id="model-diagnostics-1" class="level4">
<h4 class="anchored" data-anchor-id="model-diagnostics-1">Model Diagnostics:</h4>
<ul>
<li><strong>R-squared (Within)</strong>: At 0.3407, around 34.07% of the variation in property crime rates is explained by the model within entities.</li>
<li><strong>F-statistic</strong>: Highly significant (p-value &lt; 0.0001), indicating the collective significance of the variables.</li>
<li><strong>Poolability Test</strong>: The significant F-test for poolability highlights the importance of entity and time effects.</li>
</ul>
</section>
</section>
<section id="comparative-analysis-and-implications" class="level3">
<h3 class="anchored" data-anchor-id="comparative-analysis-and-implications">Comparative Analysis and Implications:</h3>
<ul>
<li><strong>Effectiveness of Interventions</strong>: Model 1 shows a significant reduction in violent crime rates in high-crime areas post-intervention, while Model 2 does not find a significant impact on property crime rates. This discrepancy could be due to differences in the nature of violent versus property crimes or the effectiveness of interventions in these domains.</li>
<li><strong>Role of Employment and Population</strong>: Neither model finds a significant relationship between employment and crime rates. However, population changes are significantly related to property crime rates in Model 2, suggesting a possible differential impact on different types of crimes.</li>
<li><strong>Model Robustness</strong>: The significant poolability tests in both models underscore the importance of considering both entity (e.g., geographic) and time effects in analyzing crime rate changes.</li>
</ul>
<p>These findings contribute to the broader discourse on the effectiveness of crime interventions and the dynamics of crime rate determinants. The significant impact in high-crime areas for violent crimes (Model 1) suggests that targeted policies may be effective in these contexts. However, the lack of significance in property crime reduction (Model 2) calls for a reevaluation of strategies or further investigation into different or additional determinants that might influence property crime rates.</p>
</section>
</section>
<section id="event-study" class="level2">
<h2 class="anchored" data-anchor-id="event-study"><strong>Event Study:</strong></h2>
<div class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-15-output-1.png" width="1141" height="565"></p>
</div>
</div>
<div class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-16-output-1.png" width="1141" height="565"></p>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="cell-output cell-output-stderr">
<pre><code>R[write to console]: Variance contained negative values in the diagonal and was 'fixed' (a la Cameron, Gelbach &amp; Miller 2011).
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="16">
<p><img src="Final-Edit_files/figure-html/cell-17-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="17">
<div class="cell-output cell-output-stderr">
<pre><code>R[write to console]: Variance contained negative values in the diagonal and was 'fixed' (a la Cameron, Gelbach &amp; Miller 2011).
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="17">
<p><img src="Final-Edit_files/figure-html/cell-18-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="robustness-checks" class="level2">
<h2 class="anchored" data-anchor-id="robustness-checks"><strong>Robustness Check(s):</strong></h2>
<section id="check-01-synthetic-controls" class="level4">
<h4 class="anchored" data-anchor-id="check-01-synthetic-controls"><strong>Check #01: Synthetic Controls</strong></h4>
<p>Synthetic Control Models (SCM) were first proposed and estimated by economists Alberto Abadie and Javier Gardeazabal in their <a href="https://economics.mit.edu/sites/default/files/publications/The%20Economic%20Costs%20of%20Conflict.pdf">2003 paper</a>, where they investigated the economic effects of conflict, specifically focusing on the terrorist conflict in the Basque Country. SCM works by creating a ‘Synthetic’ replica of a treated unit that received some intervention at time t. This approach is particularly useful when other, more suitable candidates for comparison might not exist or are unavailable. SCM accomplishes this by generating a set of non-negative weights that sum to 1, derived from a pool of untreated candidates. These candidates are selected for their similarity in characteristics to the treated unit of interest prior to the intervention. This methodology allows for a more accurate assessment of the intervention’s impact by comparing the post-intervention outcomes of the treated unit with those of the synthetic control.</p>
</section>
<section id="againsts-a-difference-in-difference-model" class="level4">
<h4 class="anchored" data-anchor-id="againsts-a-difference-in-difference-model"><strong>Againsts a Difference-in-Difference Model</strong></h4>
<p>The Synthetic Control Model (SCM) is employed as a robustness check for the Difference-in-Differences (DiD) analysis to enhance the credibility and reliability of our findings. SCM is particularly adept at constructing a counterfactual scenario in cases where parallel trends assumptions, crucial for DiD validity, might be questionable. By using a weighted combination of untreated units to create a synthetic control group, SCM provides a more nuanced and context-specific comparison, addressing potential limitations in the DiD model such as the presence of idiosyncratic trends that are not common to all units. This complementary approach helps to reinforce the validity of our causal inferences, ensuring that the observed effects are not artifacts of model specification but robust to alternative analytical frameworks.</p>
</section>
<section id="application" class="level4">
<h4 class="anchored" data-anchor-id="application"><strong>Application</strong></h4>
<p>Below, you’ll find three Synthetic Contron Model estimations. The first is a model that makes use of <a href="https://scipy.github.io/devdocs/reference/generated/scipy.optimize.nnls.html">Non-Negative Least Squares</a> to generate the weights needed to construct a Synthetic replica of California. The following two interations make use of an optimization model <a href="https://docs.scipy.org/doc/scipy/reference/optimize.minimize-neldermead.html">Nelder-Mead</a> optimization that incorporates a Non-Negative Least Squares framework, augmented by the introduction of a diagonal matrix <code>V</code>. The elements of <code>V</code> function as weights, indicating the relative significance of various variables within the model. This matrix is crucial for fine-tuning the model’s outputs, ensuring that the weights are applied in a manner that sensitively and accurately reflects the underlying data characteristics. The optimized weights, represented by <code>W*(V)</code>, are derived in such a way that they best reproduce specific target values, as encapsulated by a predefined vector of key indicators. This methodological approach allows for a nuanced and precise application of the model to a given dataset, leading to more customized and context-specific results.</p>
</section>
<section id="manual-synthetic-controls-estimation-using-non-negative-least-squares-nnls" class="level4">
<h4 class="anchored" data-anchor-id="manual-synthetic-controls-estimation-using-non-negative-least-squares-nnls"><strong>Manual Synthetic Controls Estimation Using Non-Negative Least Squares (NNLS)</strong></h4>
<div class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-19-output-1.png" width="1122" height="597"></p>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-20-output-1.png" width="1122" height="597"></p>
</div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results"><strong>Results:</strong></h2>
<p>The two figures above depict synthetic California’s property and violent crime rates from 1986 to 2002, juxtaposed with the actual crime rates of California during the same timeframe. In both models, synthetic California’s crime rates closely track the actual data, lending credibility to the NNLS estimation technique. Following the 1994 enactment of the VCCA, a significant gap emerges between the actual and synthetic data, indicating that, shortly after 1994, there is a discernible difference between the synthetic, untreated California and its actual crime rates, providing a strong visual representation of the effects of the 1994 crime bill.</p>
<section id="quirks" class="level4">
<h4 class="anchored" data-anchor-id="quirks"><strong>Quirks</strong></h4>
<p>In both graphs, there is a noticeable divergence between the synthetic and actual data pre-1994, specifically in 1993. At this stage, the cause of this divergence is analytically unknown, but my educated guess would suggest there’s an anticipatory effect taking hold in California in 1993, spurring this divergence. To fully flsuh out this anomaly, a more careful investigation will need to take place to determine the source and full implications of this sudden and unexpected divergence.</p>
</section>
</section>
<section id="implementation-of-synthetic-controls-using-pysyncon-package-2003-optimization" class="level2">
<h2 class="anchored" data-anchor-id="implementation-of-synthetic-controls-using-pysyncon-package-2003-optimization"><strong>Implementation of Synthetic Controls Using Pysyncon Package &amp; 2003 Optimization</strong></h2>
<div class="cell" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">V</th>
<th data-quarto-table-cell-role="th">treated</th>
<th data-quarto-table-cell-role="th">synthetic</th>
<th data-quarto-table-cell-role="th">sample mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">violent_crime_rate</td>
<td>0.245</td>
<td>892.894</td>
<td>892.506</td>
<td>521.786</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">GDP</td>
<td>0.249</td>
<td>922830.938</td>
<td>588289.312</td>
<td>132020.023</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">population</td>
<td>0.247</td>
<td>31003.360</td>
<td>18182.309</td>
<td>4893.066</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">employment</td>
<td>0.259</td>
<td>12741.788</td>
<td>8093.412</td>
<td>2192.868</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-24-output-1.png" width="602" height="411"></p>
</div>
</div>
<section id="weights-actual-vs-synthetic" class="level4">
<h4 class="anchored" data-anchor-id="weights-actual-vs-synthetic"><strong>Weights, Actual Vs Synthetic</strong></h4>
<div class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<p><img src="Final-Edit_files/figure-html/cell-25-output-1.png" width="602" height="411"></p>
</div>
</div>
</section>
</section>
<section id="results-1" class="level2">
<h2 class="anchored" data-anchor-id="results-1"><strong>Results:</strong></h2>
<p>The two graphs above, generated using the synthetic control method as outlined by Abadie and colleagues, suggest that the underlying features used to create the weights for estimating a valid synthetic control are inadequate. Consequently, this inadequacy hampers the creation of a valid synthetic counterpart for California. Both graphs demonstrate that post-1994, the actual violent and property crime rates in California exceeded those of the synthetic California. This discrepancy might be attributed to the well-documented issue of <a href="https://academic.oup.com/aler/article-abstract/21/1/81/5210860?redirectedFrom=fulltext">Reverse Causality</a>. Typically, studies in this field estimate an IV 2SLS model to disentangle these effects.</p>
<section id="abadie-et-al.-vs.-nnls" class="level4">
<h4 class="anchored" data-anchor-id="abadie-et-al.-vs.-nnls"><strong>Abadie et al.&nbsp;vs.&nbsp;NNLS:</strong></h4>
<p>Regarding the Synthetic Controls Models estimated above: While the Non-Negative Least Squares (NNLS) method produced results more aligned with the previously estimated Difference-in-Difference models, the implementation following the exact formula by Abadie et al.&nbsp;carries more credibility due to its strong foundation in the literature.</p>
<p>Currently, the findings indicate that the estimates derived from the Difference-in-Difference models mentioned earlier lack robustness.</p>
</section>
<section id="check-02-difference-in-difference-estimation-using-1988-2000-time-frame" class="level4">
<h4 class="anchored" data-anchor-id="check-02-difference-in-difference-estimation-using-1988-2000-time-frame"><strong>Check-02:</strong> Difference-in-Difference Estimation Using 1988-2000 Time Frame</h4>
</section>
<section id="model-02a-re-estimated-using-reduced-time-frame" class="level4">
<h4 class="anchored" data-anchor-id="model-02a-re-estimated-using-reduced-time-frame">Model-02A Re-estimated Using Reduced Time Frame</h4>
<div class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>PanelOLS Estimation Summary</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>violent_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.1794</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Estimator:</td>
<td>PanelOLS</td>
<td data-quarto-table-cell-role="th">R-squared (Between):</td>
<td>-1.7182</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>507</td>
<td data-quarto-table-cell-role="th">R-squared (Within):</td>
<td>0.2471</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, Dec 12 2023</td>
<td data-quarto-table-cell-role="th">R-squared (Overall):</td>
<td>-1.6767</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:49</td>
<td data-quarto-table-cell-role="th">Log-likelihood</td>
<td>-2792.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cov. Estimator:</td>
<td>Clustered</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>33.018</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Entities:</td>
<td>39</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,453)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th">F-statistic (robust):</td>
<td>28.497</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time periods:</td>
<td>13</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,453)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Parameter Estimates</caption>
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">Parameter</td>
<td data-quarto-table-cell-role="th">Std. Err.</td>
<td data-quarto-table-cell-role="th">T-stat</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td data-quarto-table-cell-role="th">Lower CI</td>
<td data-quarto-table-cell-role="th">Upper CI</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">employment</td>
<td>-0.0285</td>
<td>0.0607</td>
<td>-0.4691</td>
<td>0.6392</td>
<td>-0.1479</td>
<td>0.0909</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">population</td>
<td>-0.0394</td>
<td>0.0229</td>
<td>-1.7172</td>
<td>0.0866</td>
<td>-0.0845</td>
<td>0.0057</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Post_HC</td>
<td>-99.207</td>
<td>49.586</td>
<td>-2.0007</td>
<td>0.0460</td>
<td>-196.66</td>
<td>-1.7591</td>
</tr>
</tbody>
</table>
<br><br>F-test for Poolability: 95.305<br>P-value: 0.0000<br>Distribution: F(50,453)<br><br>Included effects: Entity, Time
</div>
</div>
</section>
<section id="model-02b-re-estimated-using-reduced-time-frame" class="level4">
<h4 class="anchored" data-anchor-id="model-02b-re-estimated-using-reduced-time-frame">Model-02B Re-estimated Using Reduced Time Frame</h4>
<div class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>PanelOLS Estimation Summary</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>property_crime_rate</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.2108</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Estimator:</td>
<td>PanelOLS</td>
<td data-quarto-table-cell-role="th">R-squared (Between):</td>
<td>-1.8918</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>507</td>
<td data-quarto-table-cell-role="th">R-squared (Within):</td>
<td>0.3486</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, Dec 12 2023</td>
<td data-quarto-table-cell-role="th">R-squared (Overall):</td>
<td>-1.8639</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:05:49</td>
<td data-quarto-table-cell-role="th">Log-likelihood</td>
<td>-3612.9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cov. Estimator:</td>
<td>Clustered</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>40.341</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Entities:</td>
<td>39</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,453)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>13.000</td>
<td data-quarto-table-cell-role="th">F-statistic (robust):</td>
<td>21.537</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th">P-value</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time periods:</td>
<td>13</td>
<td data-quarto-table-cell-role="th">Distribution:</td>
<td>F(3,453)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Avg Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Min Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Max Obs:</td>
<td>39.000</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td></td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Parameter Estimates</caption>
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">Parameter</td>
<td data-quarto-table-cell-role="th">Std. Err.</td>
<td data-quarto-table-cell-role="th">T-stat</td>
<td data-quarto-table-cell-role="th">P-value</td>
<td data-quarto-table-cell-role="th">Lower CI</td>
<td data-quarto-table-cell-role="th">Upper CI</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">employment</td>
<td>0.0692</td>
<td>0.2894</td>
<td>0.2392</td>
<td>0.8110</td>
<td>-0.4995</td>
<td>0.6379</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">population</td>
<td>-0.4976</td>
<td>0.1732</td>
<td>-2.8730</td>
<td>0.0043</td>
<td>-0.8380</td>
<td>-0.1572</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Post_PC</td>
<td>-151.36</td>
<td>188.73</td>
<td>-0.8020</td>
<td>0.4230</td>
<td>-522.26</td>
<td>219.54</td>
</tr>
</tbody>
</table>
<br><br>F-test for Poolability: 70.927<br>P-value: 0.0000<br>Distribution: F(50,453)<br><br>Included effects: Entity, Time
</div>
</div>
</section>
<section id="results-2" class="level4">
<h4 class="anchored" data-anchor-id="results-2"><strong>Result(s)</strong></h4>
<p><strong>Model-02A:</strong> when re-estimated over a shorter time frame (1988-2000, instead of 1986-2002), displays consistent significance for the key variable “PostHC_static.” However, there is a noticeable decrease in the estimated magnitude of its effect, dropping from -114.69 to -99.207. In context, this change suggests that shortening the time range by four periods reduces the estimated impact of being a high-crime state post the 1994 implementation of the VCCA by approximately 15.48 violent crimes per 100,000.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>